[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#667eea"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#222222"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
